(source melpa)
(source gnu)
(source org)
(development
 (depends-on "lean" :git "https://github.com/leanprover/lean.git" :files ("src/emacs/*.el"))
 (depends-on "cl-lib")
 (depends-on "dash" 2.8.0)
 (depends-on "dash-functional" 1.1.0)
 (depends-on "f")
 (depends-on "company")
 (depends-on "flymake")
 (depends-on "s")
 (depends-on "org-plus-contrib")
 (depends-on "htmlize"))
