name = "tpil-examples"
version = "0.1.0"
defaultTargets = ["Examples"]

[[require]]
name = "subverso"
git = "../../lean/subverso" # "https://github.com/leanprover/subverso.git"
rev = "signature-noncomp"



[[lean_lib]]
name = "Examples"
