name: mdbook deploy to Netlify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download mdbook and dependencies for Lean
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH

        curl -O --location https://github.com/leanprover/mdBook/releases/download/v0.4.6/mdbook-linux.tar.gz
        tar xvf mdbook-linux.tar.gz
        cp ./mdbook-linux/mdbook $HOME/.local/bin/
        ldd ./mdbook-linux/mdbook
        mdbook --help

        curl -O --location https://github.com/badboy/mdbook-toc/releases/download/0.14.2/mdbook-toc-0.14.2-x86_64-unknown-linux-gnu.tar.gz
        tar xvf mdbook-toc-0.14.2-x86_64-unknown-linux-gnu.tar.gz
        cp ./mdbook-toc $HOME/.local/bin/
        ldd ./mdbook-toc
        mdbook-toc --help
    - name: Run mdbook build
      shell: bash
      run: |
        mdbook build
        rm -rf ./out/.git
        rm -rf ./out/.github
    - name: Deploy to Netlify hosting
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: out
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: |
          ${{ github.event_name == 'pull_request' && format('pr#{0}: {1}', github.event.number, github.event.pull_request.title) || format('ref/{0}: {1}', github.ref_name, steps.deploy-info.outputs.message) }}
        alias: ${{ steps.deploy-info.outputs.alias }}
        enable-commit-comment: false
        enable-pull-request-comment: false
        github-deployment-environment: "lean-lang.org/theorem_proving_in_lean4"
        fails-without-credentials: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: "51300c89-2f6c-4bba-a575-8cf12e434502"
